#!/bin/bash
#SBATCH --partition          h3c
#SBATCH --time               24:00:00
#SBATCH --nodes              1
#SBATCH --ntasks-per-node    48
#SBATCH --cpus-per-task      1

# Load Modules
module load hdf5/intel
module load qe/7.2_intel
export HDF5_USE_FILE_LOCKING="FALSE"

echo "Job Running ..."

JOB='pert'
EXE='perturbo.x'
mpirun -n $SLURM_NTASKS $EXE -npools $SLURM_NTASKS \
        < $JOB.in > $JOB.out

echo "Job Done!"
