#!/bin/bash
#SBATCH --partition          h3c
#SBATCH --time               24:00:00
#SBATCH --nodes              1
#SBATCH --ntasks-per-node    48
#SBATCH --cpus-per-task      1

# Load Modules
module load hdf5/intel
module load qe/7.2_intel

echo "Job Running ..."

JOB='qe2pert'
EXE='qe2pert.x'
mpirun -n $SLURM_NTASKS $EXE -npools $SLURM_NTASKS < $JOB.in > $JOB.out

echo "Job Done!"
